openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/signup:
    post:
      summary: 'User Registration'
      operationId: userRegistration
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Auth routes'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: fclfxrzydfjbwo
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: joanny24@example.com
                password:
                  type: string
                  description: 'Must be at least 6 characters. Must not be greater than 255 characters.'
                  example: '"bD9U1Id`'
                confirm_password:
                  type: string
                  description: 'The value and <code>password</code> must match.'
                  example: vitae
              required:
                - name
                - email
                - password
                - confirm_password
      security: []
  /api/login:
    post:
      summary: Login
      operationId: login
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Auth routes'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: kub.jerome@example.org
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: ',IrUKLA0{6E9D'
              required:
                - email
                - password
      security: []
  /api/profile/data:
    get:
      summary: 'Get Profile Data'
      operationId: getProfileData
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Profile
  /api/reset-password-link:
    post:
      summary: 'Sending reset password link'
      operationId: sendingResetPasswordLink
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Reset password'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: buckridge.keely@example.net
              required:
                - email
      security: []
  /api/reset-password:
    post:
      summary: 'Password reset'
      operationId: passwordReset
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Reset password'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: ''
                  example: labore
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: Jti9B)j4i-Ho
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: kenyon.wunsch@example.net
              required:
                - token
                - password
                - email
      security: []
tags:
  -
    name: 'Auth routes'
    description: ''
  -
    name: Profile
    description: ''
  -
    name: 'Reset password'
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
