openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/signup:
    post:
      summary: 'User Registration'
      operationId: userRegistration
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Auth routes'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: yffgnn
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: kassulke.kylie@example.com
                password:
                  type: string
                  description: 'Must be at least 6 characters. Must not be greater than 255 characters.'
                  example: 'W+h&Z+<=hvT'
                confirm_password:
                  type: string
                  description: 'The value and <code>password</code> must match.'
                  example: repellendus
              required:
                - name
                - email
                - password
                - confirm_password
      security: []
  /api/login:
    post:
      summary: Login
      operationId: login
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Auth routes'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: jmurray@example.com
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: '9BD!cX"(Ma17rfM$BP'
              required:
                - email
                - password
      security: []
  /api/profile/data:
    get:
      summary: 'Get Profile Data'
      operationId: getProfileData
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: true
                  status_code: 200
                  message: ''
                  data:
                    id: ac49ffdc-8568-481c-8587-5cb3f846af5f
                    name: 'test update'
                    email: hassanshahriar18@gmail.com
                    user_type: User
                    login_type: default
                    dob: '2022-01-01'
                    phone: '11111111111'
                    created_at: '2023-05-11T07:16:47.000000Z'
                    updated_at: '2023-05-11T17:36:39.000000Z'
                    deleted_at: null
                properties:
                  status:
                    type: boolean
                    example: true
                  status_code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: ''
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: ac49ffdc-8568-481c-8587-5cb3f846af5f
                      name:
                        type: string
                        example: 'test update'
                      email:
                        type: string
                        example: hassanshahriar18@gmail.com
                      user_type:
                        type: string
                        example: User
                      login_type:
                        type: string
                        example: default
                      dob:
                        type: string
                        example: '2022-01-01'
                      phone:
                        type: string
                        example: '11111111111'
                      created_at:
                        type: string
                        example: '2023-05-11T07:16:47.000000Z'
                      updated_at:
                        type: string
                        example: '2023-05-11T17:36:39.000000Z'
                      deleted_at:
                        type: string
                        example: null
      tags:
        - Profile
  /api/profile/update:
    post:
      summary: 'Update Profile'
      operationId: updateProfile
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ''
                  example: architecto
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: pkqrnbdecqwnhtapmuucgu
                dob:
                  type: string
                  description: 'Must be a valid date in the format <code>Y-m-d</code>.'
                  example: '2023-05-13'
                phone:
                  type: string
                  description: 'Must be 11 characters.'
                  example: aosmqnrixfv
              required:
                - id
                - name
  /api/reset-password-link:
    post:
      summary: 'Sending reset password link'
      operationId: sendingResetPasswordLink
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Reset password'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: thora.toy@example.org
              required:
                - email
      security: []
  /api/reset-password:
    post:
      summary: 'Password reset'
      operationId: passwordReset
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Reset password'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: ''
                  example: voluptas
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: "n{R'we%P`*h4"
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: coby73@example.com
              required:
                - token
                - password
                - email
      security: []
  /api/resume/contact:
    post:
      summary: 'create or update contact'
      operationId: createOrUpdateContact
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Resume
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ''
                  example: dolorem
                first_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: nvrooecocfxeryt
                last_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: mgjowenzprzihwozbpiimfda
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: derek.schumm@example.org
                job_title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: ofct
                phone:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: xqzysbwdnlmrpmppdmgyw
                location:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: gdigmhszcornjpdorkawuv
                linkedin_link:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: kqmqofyzeqaonlywpru
                facebook_link:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: maduvwa
                twitter_link:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: dljarjhnu
                website:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: t
              required:
                - id
                - first_name
                - last_name
                - email
                - job_title
                - phone
                - location
tags:
  -
    name: 'Auth routes'
    description: ''
  -
    name: Profile
    description: ''
  -
    name: 'Reset password'
    description: ''
  -
    name: Resume
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
