openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/signup:
    post:
      summary: 'User Registration'
      operationId: userRegistration
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Auth routes'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: aggku
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: hermiston.kacie@example.org
                password:
                  type: string
                  description: 'Must be at least 6 characters. Must not be greater than 255 characters.'
                  example: 'l=mJL<g8T,<qx+@CJ0e'
                confirm_password:
                  type: string
                  description: 'The value and <code>password</code> must match.'
                  example: fugiat
              required:
                - name
                - email
                - password
                - confirm_password
      security: []
  /api/login:
    post:
      summary: Login
      operationId: login
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Auth routes'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: ashtyn68@example.org
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: 'b)jW"L`q*;d>?`,a'
              required:
                - email
                - password
      security: []
  /api/profile/data:
    get:
      summary: 'Get Profile Data'
      operationId: getProfileData
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: true
                  status_code: 200
                  message: ''
                  data:
                    id: ac49ffdc-8568-481c-8587-5cb3f846af5f
                    name: 'test update'
                    email: hassanshahriar18@gmail.com
                    user_type: User
                    login_type: default
                    dob: '2022-01-01'
                    phone: '11111111111'
                    created_at: '2023-05-11T07:16:47.000000Z'
                    updated_at: '2023-05-11T17:36:39.000000Z'
                    deleted_at: null
                properties:
                  status:
                    type: boolean
                    example: true
                  status_code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: ''
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: ac49ffdc-8568-481c-8587-5cb3f846af5f
                      name:
                        type: string
                        example: 'test update'
                      email:
                        type: string
                        example: hassanshahriar18@gmail.com
                      user_type:
                        type: string
                        example: User
                      login_type:
                        type: string
                        example: default
                      dob:
                        type: string
                        example: '2022-01-01'
                      phone:
                        type: string
                        example: '11111111111'
                      created_at:
                        type: string
                        example: '2023-05-11T07:16:47.000000Z'
                      updated_at:
                        type: string
                        example: '2023-05-11T17:36:39.000000Z'
                      deleted_at:
                        type: string
                        example: null
      tags:
        - Profile
  /api/profile/update:
    post:
      summary: 'Update Profile'
      operationId: updateProfile
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ''
                  example: voluptatibus
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: gosejcsrtjfmmzmmqdqmue
                dob:
                  type: string
                  description: 'Must be a valid date in the format <code>Y-m-d</code>.'
                  example: '2023-05-13'
                phone:
                  type: string
                  description: 'Must be 11 characters.'
                  example: gjfdomqchbc
              required:
                - id
                - name
  /api/reset-password-link:
    post:
      summary: 'Sending reset password link'
      operationId: sendingResetPasswordLink
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Reset password'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: marilyne.strosin@example.net
              required:
                - email
      security: []
  /api/reset-password:
    post:
      summary: 'Password reset'
      operationId: passwordReset
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Reset password'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: ''
                  example: velit
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: 'n6IElbMix&+'
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: junius.nicolas@example.com
              required:
                - token
                - password
                - email
      security: []
  /api/resume/contact:
    post:
      summary: 'create or update contact'
      operationId: createOrUpdateContact
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Resume
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ''
                  example: dolor
                first_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: klgkuszhlfcg
                last_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: cqzetakwisdklnelnbq
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: joan83@example.com
                job_title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: zapivroeyqjxadkr
                phone:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: mugojwikbelovsl
                location:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: ggnarbwffmzfizxfvo
                linkedin_link:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: rmncgmxzrlzgk
                facebook_link:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: pxpegpfkjkafpbjey
                twitter_link:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: kbajxpxscfqyrjk
                website:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: nibcnohxpp
              required:
                - id
                - first_name
                - last_name
                - email
                - job_title
                - phone
                - location
  /api/resume/education:
    post:
      summary: 'create or update education'
      operationId: createOrUpdateEducation
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Resume
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ''
                  example: null
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: pudmkkpzwayqezpfsvwfmamkj
                school_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: mzyyanellmuxpyrr
                location:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: owpqpkt
                feild_of_study:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: rppudexc
                start_date:
                  type: string
                  description: 'Must be a valid date in the format <code>Y-m-d</code>.'
                  example: '2023-05-13'
                active:
                  type: boolean
                  description: ''
                  example: true
                end_date:
                  type: string
                  description: 'Must be a valid date in the format <code>Y-m-d</code>. This field is required when <code>active</code> is <code>true</code>.'
                  example: '2023-05-13'
              required:
                - name
                - school_name
                - start_date
                - active
tags:
  -
    name: 'Auth routes'
    description: ''
  -
    name: Profile
    description: ''
  -
    name: 'Reset password'
    description: ''
  -
    name: Resume
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
